**Mini Project**
Airline Tweet Sentiment Classifier using Natural Language Processing**
---
**Notes:**
Use sample dataset:
https://github.com/salman1256/aimltraining/blob/main/Day-30/airline_tweets_sample.csv

---
# Steps:
1. Import libraries  
2. Load and explore dataset  
3. Clean and preprocess the text  
4. Convert text to numerical vectors (TF-IDF)  
5. Split into train and test sets  
6. Train a Logistic Regression model  
7. Evaluate accuracy and classification report  
8. Predict sentiment for new example tweets

In [192]:
# Step 1 a: Import Required Libraries
import pandas as pd
import numpy as np
import nltk
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [193]:
# Step 1 b: Download nltk required thing like stopwords
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

stop_words= set(stopwords.words('english'))
stemmer=PorterStemmer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [194]:
#Step 2 a: Load DataSet
df=pd.read_csv('/content/airline_tweets_sample.csv')

In [195]:
#Step 2 : Check Data set at least top 5 values
df.head()

                                                text sentiment
0  @United flight was delayed for 3 hours, worst ...  negative
1  Loved the service on @Delta, crew was super fr...  positive
2  @AmericanAir lost my luggage again, so disappo...  negative
3  Smooth boarding and on-time arrival. Great job...  positive
4  The seats were uncomfortable but staff was polite   neutral

In [ ]:
# Step 3:
#Text Cleaning and Preprocessing
# For each tweet do:
# a. Convert to lowercase
# b. Remove URLs
# c. Remove special characters and numbers
# d. Remove stopwords (common words like *the, is, and* etc.)
# e. Apply **stemming** (reduce words to their root form)

In [207]:
def clean_text(text):
    text = str(text).lower() #convert to lowercase
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r'http\S+', '', text) # remove URLs
    text=re.sub(r'[^a-z\s]','',text) # remove special character and numbers
    words = [word for word in text.split() if word not in stopwords.words('english')]
    stemmed = [stemmer.stem(word) for word in words]
    return ' '.join(stemmed)

In [208]:
df['cleaned_text']=df['text'].apply(clean_text)
df

,text,sentiment,cleaned_text
0,"@United flight was delayed for 3 hours, worst ...",negative,unit flight delay hour worst experi ever
1,"Loved the service on @Delta, crew was super fr...",positive,love servic delta crew super friendli
2,"@AmericanAir lost my luggage again, so disappo...",negative,americanair lost luggag disappoint
3,Smooth boarding and on-time arrival. Great job...,positive,smooth board ontim arriv great job southwestair
4,The seats were uncomfortable but staff was polite,neutral,seat uncomfort staff polit
5,"@JetBlue flight attendants were rude, not flyi...",negative,jetblu flight attend rude fli
6,"Got a free upgrade to business class, thank yo...",positive,got free upgrad busi class thank unit
7,"Average flight, nothing special to mention",neutral,averag flight noth special mention
8,@DeltaAirLines provided excellent support with...,positive,deltaairlin provid excel support book
9,The in-flight entertainment was not working,negative,inflight entertain work
10,Snacks were good but the legroom was terrible,negative,snack good legroom terribl
11,@SouthwestAir always makes flying fun!,positive,southwestair alway make fli fun
12,Check-in process was quick and easy,positive,checkin process quick easi
13,Customer service kept me on hold for 40 minutes,negative,custom servic kept hold minut
14,"Flight was okay, staff were fine, nothing to c...",neutral,flight okay staff fine noth complain
15,"Super smooth landing, kudos to the pilot",positive,super smooth land kudo pilot
16,I missed my connection because of their delay,negative,miss connect delay
17,@AmericanAir helped me rebook my flight quickly,positive,americanair help rebook flight quickli
18,Cabin was clean and comfortable,positive,cabin clean comfort
19,"They refused to change my seat, very unhelpful",negative,refus chang seat unhelp
20,"Just an ordinary flight, everything was normal",neutral,ordinari flight everyth normal
21,Loved the new in-flight menu options,positive,love new inflight menu option
22,Baggage claim took forever,negative,baggag claim took forev
23,Polite crew but very noisy cabin,neutral,polit crew noisi cabin
24,@UnitedAirlines app kept crashing during check-in,negative,unitedairlin app kept crash checkin
25,"Had extra legroom and free snacks, amazing!",positive,extra legroom free snack amaz
26,Boarding was chaotic and disorganized,negative,board chaotic disorgan
27,Comfortable seats and great WiFi on board,positive,comfort seat great wifi board
28,Staff did their best despite the delay,neutral,staff best despit delay
29,Worst airline experience in years,negative,worst airlin experi year

In [209]:
#Step: 4
#a) Convert text to numerical vectors (TF-IDF)
# b) check X,y and shape len

tfidf=TfidfVectorizer(max_features=5000, stop_words='english', sublinear_tf=True)
X = tfidf.fit_transform(df['cleaned_text'])
y = df['sentiment']

print("Shape of X:", X.shape)
print("Length of y:", len(y))

Shape of X: (30, 104)
Length of y: 30

In [210]:
# Step 5: Split into train and test sets
# 80% training and 20% testing
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,stratify=y, random_state=42)

In [211]:
# Step:6 Train a Logistic Regression model
# a: Create Logistic Model
# b: Train Logistic Model
model=LogisticRegression(multi_class='ovr',max_iter=1000)
model.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(

LogisticRegression(max_iter=1000, multi_class='ovr')

In [212]:
#Step 7:
# Evaluate accuracy and classification report
# a. predict Model
# b. Precision, reacll, F1-Score for each sentiments
y_pred=model.predict(X_test)
print("Accuracy: ",accuracy_score(y_test,y_pred))
print("Classification Report:\n", classification_report(y_test,y_pred))

Accuracy:  0.3333333333333333
Classification Report:
               precision    recall  f1-score   support

    negative       0.00      0.00      0.00         3
     neutral       0.00      0.00      0.00         1
    positive       0.33      1.00      0.50         2

    accuracy                           0.33         6
   macro avg       0.11      0.33      0.17         6
weighted avg       0.11      0.33      0.17         6

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [213]:
#Step 8: Predict sentiment for new example tweets

new_tweet=[
    'I love how smooth the flight was!',
    'Terrible experience, I never flying with them again.',
    'Super friendly staff and clean cabin, I love it!',
    'Delayed again, this airline never learns.',
    'The sit was uncomfortable but the staff is polite.',
    'The staff is polite but the cabin is noisy.'
]

new_clean_tweet=[clean_text(tweet) for tweet in new_tweet]
new_clean_tweet_vec=tfidf.transform(new_clean_tweet)
new_pred=model.predict(new_clean_tweet_vec)

print('\n Prediction are: ')
for tweet, new_pred in zip(new_tweet,new_pred):
  print(f" {tweet} --> {new_pred} ")

 Prediction are:
 I love how smooth the flight was! --> positive
 Terrible experience, I never flying with them again. --> negative
 Super friendly staff and clean cabin, I love it! --> positive
 Delayed again, this airline never learns. --> negative
 The sit was uncomfortable but the staff is polite. --> neutral
 The staff is polite but the cabin is noisy. --> neutral