In [ ]:
#***Bag of Words***

In [ ]:
#import libraries
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import re
import nltk
from nltk.corpus import stopwords
from sklearn.linear_model import LogisticRegression

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
data = {
    "review": [
        "I absolutely love this phone! The camera quality is fantastic and battery lasts all day.",
        "Terrible experience. The screen broke within a week, and customer service was useless.",
        "Great value for money. Performance is smooth and build quality feels premium.",
        "The laptop overheats and the battery drains too fast. Very disappointed.",
        "Excellent sound quality and very comfortable to wear. Highly recommend these headphones!",
        "Worst product I’ve ever bought. It stopped working after two days.",
        "Amazing performance and display. Totally worth the price.",
        "Poor design and fragile build. I regret buying this item.",
        "Fast delivery and great packaging. The product works as expected.",
        "Customer support was unhelpful. Will not buy from this brand again."
],
    "sentiment": [
    "positive", "negative", "positive", "negative", "positive",
    "negative", "positive", "negative", "positive", "negative"
]
}

In [ ]:
df=pd.DataFrame(data)
df.head()

                                              review sentiment
0  I absolutely love this phone! The camera quali...  positive
1  Terrible experience. The screen broke within a...  negative
2  Great value for money. Performance is smooth a...  positive
3  The laptop overheats and the battery drains to...  negative
4  Excellent sound quality and very comfortable t...  positive

In [ ]:
#function to lower and clean data
def clean_text(text):
  text=text.lower()
  text=re.sub(r'[^a-zA-Z0-9\s]','',text)
  text=' '.join([word for word in text.split() if word not in stopwords.words('english')])
  return text

In [ ]:
df['clean_review']=df['review'].apply(clean_text)
df

                                              review  ...                                       clean_review
0  I absolutely love this phone! The camera quali...  ...  absolutely love phone camera quality fantastic...
1  Terrible experience. The screen broke within a...  ...  terrible experience screen broke within week c...
2  Great value for money. Performance is smooth a...  ...  great value money performance smooth build qua...
3  The laptop overheats and the battery drains to...  ...  laptop overheats battery drains fast disappointed
4  Excellent sound quality and very comfortable t...  ...  excellent sound quality comfortable wear highl...
5  Worst product I’ve ever bought. It stopped wor...  ...  worst product ive ever bought stopped working ...
6  Amazing performance and display. Totally worth...  ...    amazing performance display totally worth price
7  Poor design and fragile build. I regret buying...  ...       poor design fragile build regret buying item
8  Fast delivery and great packaging. The product...  ...  fast delivery great packaging product works ex...
9  Customer support was unhelpful. Will not buy f...  ...               customer support unhelpful buy brand

[10 rows x 3 columns]

In [ ]:
cv=CountVectorizer(max_features=20)
X=cv.fit_transform(df['clean_review']).toarray()
y=df['sentiment']
cv.get_feature_names_out()

array(['amazing', 'battery', 'bought', 'brand', 'build', 'buy', 'buying',
       'camera', 'comfortable', 'customer', 'day', 'delivery', 'design',
       'disappointed', 'display', 'fast', 'great', 'performance',
       'product', 'quality'], dtype=object)

In [ ]:
# from sklearn.linear_model import LogisticRegression
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [ ]:
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [ ]:
#User prediction
# taking review from user
user_review=input("Enter your product review: ")

#clean the review
user_review=clean_text(user_review)
user_review_bow=cv.transform([user_review]).toarray()

#predict using model
user_sentiment=model.predict(user_review_bow)

# output predicted sentiment
print("\n Cleaned Review", user_review)
print("\n Predicted Sentiment: ", user_sentiment[0])

Enter your product review: the t shirt is comfy

 Cleaned Review shirt comfy

 Predicted Sentiment:  positive

In [ ]:
# PRACTICE EXERCISE

# input_text="Natural Language Processing is going to help you out in near future . You have 2 remember this!! for getting interview calls"

# Do the following Tasks:
#  1. Spilts text into words/tokens (show the individual word token)
#  2. Clean Tokens (show clean token)
#  3. Remove Stop words (Show token after removing stop words)
#  4. Stemming (Show the words in their root forms)
#  5. Lemmatization (Show lemma words)

In [ ]:
# Step 1: Import required library
import nltk
import spacy
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
#  1. Spilts text into words/tokens (show the individual word token)
input_text="Natural Language Processing is going to help you out in near future . You have 2 remember this!! for getting interview calls"

In [ ]:
#  2. Clean Tokens (show clean token)
tokens=word_tokenize(input_text)
tokens

['Natural',
 'Language',
 'Processing',
 'is',
 'going',
 'to',
 'help',
 'you',
 'out',
 'in',
 'near',
 'future',
 '.',
 'You',
 'have',
 '2',
 'remember',
 'this',
 '!',
 '!',
 'for',
 'getting',
 'interview',
 'calls']

In [ ]:
#  3. Remove Stop words (Show token after removing stop words)
clean_tokens=[re.sub(r'[^a-zA-Z]','',token.lower()) for token in tokens if token.isalpha()]
clean_tokens

['natural',
 'language',
 'processing',
 'is',
 'going',
 'to',
 'help',
 'you',
 'out',
 'in',
 'near',
 'future',
 'you',
 'have',
 'remember',
 'this',
 'for',
 'getting',
 'interview',
 'calls']

In [ ]:
stop_words=set(stopwords.words('english'))
filtered_tokens=[token for token in clean_tokens if token not in stop_words]
filtered_tokens

['natural',
 'language',
 'processing',
 'going',
 'help',
 'near',
 'future',
 'remember',
 'getting',
 'interview',
 'calls']

In [ ]:
#  4. Stemming (Show the words in their root forms)
stemmer=PorterStemmer()
stemmed_tokens=[stemmer.stem(token) for token in filtered_tokens]
#Reduce the words to their root form (not always a word from dictionary)
stemmed_tokens

['natur',
 'languag',
 'process',
 'go',
 'help',
 'near',
 'futur',
 'rememb',
 'get',
 'interview',
 'call']

In [ ]:
#  5. Lemmatization (Show lemma words)
lemmatizer=WordNetLemmatizer()
lemmatized_tokens=[lemmatizer.lemmatize(token) for token in filtered_tokens]
#convert words to their dictionary form (lemma) using POS: part of speech
lemmatized_tokens

['natural',
 'language',
 'processing',
 'going',
 'help',
 'near',
 'future',
 'remember',
 'getting',
 'interview',
 'call']

In [ ]:
tfidf=TfidfVectorizer() #term frequency in document frequency (how many times a word appear in documents)
matrix=tfidf.fit_transform(lemmatized_tokens)
matrix
df=pd.DataFrame(matrix.toarray(),columns=tfidf.get_feature_names_out())
df

    call  future  getting  going  ...  natural  near  processing  remember
0    0.0     0.0      0.0    0.0  ...      1.0   0.0         0.0       0.0
1    0.0     0.0      0.0    0.0  ...      0.0   0.0         0.0       0.0
2    0.0     0.0      0.0    0.0  ...      0.0   0.0         1.0       0.0
3    0.0     0.0      0.0    1.0  ...      0.0   0.0         0.0       0.0
4    0.0     0.0      0.0    0.0  ...      0.0   0.0         0.0       0.0
5    0.0     0.0      0.0    0.0  ...      0.0   1.0         0.0       0.0
6    0.0     1.0      0.0    0.0  ...      0.0   0.0         0.0       0.0
7    0.0     0.0      0.0    0.0  ...      0.0   0.0         0.0       1.0
8    0.0     0.0      1.0    0.0  ...      0.0   0.0         0.0       0.0
9    0.0     0.0      0.0    0.0  ...      0.0   0.0         0.0       0.0
10   1.0     0.0      0.0    0.0  ...      0.0   0.0         0.0       0.0

[11 rows x 11 columns]

In [ ]:
# TF-IDF Example 2

In [ ]:
corpus=["Python developer required with strong coding skills",
        "Experince in REST API,Automation, Jenkins, Flask and Python",
        "Looking for machine Learning engineer familiar with NLP, Supervised, Unsupervised and Deep Learning"
      ]

In [ ]:
tfdif=TfidfVectorizer()

matrix=tfdif.fit_transform(corpus)
df=pd.DataFrame(matrix.toarray(), columns=tfdif.get_feature_names_out())
df

       and       api  automation  ...  supervised  unsupervised      with
0  0.00000  0.000000    0.000000  ...    0.000000      0.000000  0.306504
1  0.26629  0.350139    0.350139  ...    0.000000      0.000000  0.000000
2  0.20213  0.000000    0.000000  ...    0.265777      0.265777  0.202130

[3 rows x 25 columns]

In [ ]:
print('\n Top Weighted Terms')
print(df.mean().sort_values(ascending=False).head(10))

 Top Weighted Terms
python       0.190931
learning     0.177185
with         0.169545
and          0.156140
coding       0.134339
skills       0.134339
developer    0.134339
strong       0.134339
required     0.134339
in           0.116713
dtype: float64

In [ ]:
#Resume Screening: guna untuk check resume (dia guna machine ni untuk cari criteria yang syarikat nak)